### ISSUE TITLE
Should we use snake_case everywhere?

### ISSUE THREAD

**Issue by masterT** [Corb3nik/rubik#35]
Backend and frontend.

**Comment by Corb3nik** [comment]
What do you mean by everywhere?
We should use the conventions of the language, so : 
 - Snake case for ruby functions
 - Snake case for python functions
 - Camel case for JavaScript functions

**Comment by masterT** [comment]
I meant snake case in JavaScript, because it is tightly linked to the backend. It is also easier to read. But we can stick to camel case if you want. If so I will open an issue to update the JavaScript code to use such a case.

**Comment by Corb3nik** [comment]
Yeah I'd stick to camelcase for JavaScript.
